connected_devices: {}
device:
  ip: 127.0.0.1
  name: localtest
mode: simulation
modules:
  pc_speaker:
    class: module.actuators.emitters.sounds.pcspeaker.PCSpeaker
    params:
      host: 127.0.0.1
      port: 9003
      sound_path: sounds/boot.wav
      upstream:
        host: 127.0.0.1
        port: 9001
